/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as UeberRouteImport } from './routes/ueber'
import { Route as SpielenRouteImport } from './routes/spielen'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KategorienRouteImport } from './routes/kategorien'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HilfeRouteImport } from './routes/hilfe'
import { Route as GebuehrenRouteImport } from './routes/gebuehren'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerkaufenGuideRouteImport } from './routes/verkaufen.guide'
import { Route as ShopHandleRouteImport } from './routes/shop.$handle'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as KategorieSlugRouteImport } from './routes/kategorie.$slug'
import { Route as AuthenticatedNachrichtenRouteImport } from './routes/_authenticated/nachrichten'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberRoute = UeberRouteImport.update({
  id: '/ueber',
  path: '/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const SpielenRoute = SpielenRouteImport.update({
  id: '/spielen',
  path: '/spielen',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorienRoute = KategorienRouteImport.update({
  id: '/kategorien',
  path: '/kategorien',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HilfeRoute = HilfeRouteImport.update({
  id: '/hilfe',
  path: '/hilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const GebuehrenRoute = GebuehrenRouteImport.update({
  id: '/gebuehren',
  path: '/gebuehren',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerkaufenGuideRoute = VerkaufenGuideRouteImport.update({
  id: '/verkaufen/guide',
  path: '/verkaufen/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopHandleRoute = ShopHandleRouteImport.update({
  id: '/shop/$handle',
  path: '/shop/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorieSlugRoute = KategorieSlugRouteImport.update({
  id: '/kategorie/$slug',
  path: '/kategorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNachrichtenRoute = AuthenticatedNachrichtenRouteImport.update({
  id: '/nachrichten',
  path: '/nachrichten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gebuehren': typeof GebuehrenRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kategorien': typeof KategorienRoute
  '/kontakt': typeof KontaktRoute
  '/redeem': typeof RedeemRoute
  '/spielen': typeof SpielenRoute
  '/ueber': typeof UeberRoute
  '/warenkorb': typeof WarenkorbRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/verkaufen/guide': typeof VerkaufenGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gebuehren': typeof GebuehrenRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kategorien': typeof KategorienRoute
  '/kontakt': typeof KontaktRoute
  '/redeem': typeof RedeemRoute
  '/spielen': typeof SpielenRoute
  '/ueber': typeof UeberRoute
  '/warenkorb': typeof WarenkorbRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/verkaufen/guide': typeof VerkaufenGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gebuehren': typeof GebuehrenRoute
  '/hilfe': typeof HilfeRoute
  '/impressum': typeof ImpressumRoute
  '/kategorien': typeof KategorienRoute
  '/kontakt': typeof KontaktRoute
  '/redeem': typeof RedeemRoute
  '/spielen': typeof SpielenRoute
  '/ueber': typeof UeberRoute
  '/warenkorb': typeof WarenkorbRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/kategorie/$slug': typeof KategorieSlugRoute
  '/listing/$id': typeof ListingIdRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/verkaufen/guide': typeof VerkaufenGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/auth'
    | '/browse'
    | '/cookies'
    | '/datenschutz'
    | '/gebuehren'
    | '/hilfe'
    | '/impressum'
    | '/kategorien'
    | '/kontakt'
    | '/redeem'
    | '/spielen'
    | '/ueber'
    | '/warenkorb'
    | '/dashboard'
    | '/nachrichten'
    | '/kategorie/$slug'
    | '/listing/$id'
    | '/shop/$handle'
    | '/verkaufen/guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/browse'
    | '/cookies'
    | '/datenschutz'
    | '/gebuehren'
    | '/hilfe'
    | '/impressum'
    | '/kategorien'
    | '/kontakt'
    | '/redeem'
    | '/spielen'
    | '/ueber'
    | '/warenkorb'
    | '/dashboard'
    | '/nachrichten'
    | '/kategorie/$slug'
    | '/listing/$id'
    | '/shop/$handle'
    | '/verkaufen/guide'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/auth'
    | '/browse'
    | '/cookies'
    | '/datenschutz'
    | '/gebuehren'
    | '/hilfe'
    | '/impressum'
    | '/kategorien'
    | '/kontakt'
    | '/redeem'
    | '/spielen'
    | '/ueber'
    | '/warenkorb'
    | '/_authenticated/dashboard'
    | '/_authenticated/nachrichten'
    | '/kategorie/$slug'
    | '/listing/$id'
    | '/shop/$handle'
    | '/verkaufen/guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CookiesRoute: typeof CookiesRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GebuehrenRoute: typeof GebuehrenRoute
  HilfeRoute: typeof HilfeRoute
  ImpressumRoute: typeof ImpressumRoute
  KategorienRoute: typeof KategorienRoute
  KontaktRoute: typeof KontaktRoute
  RedeemRoute: typeof RedeemRoute
  SpielenRoute: typeof SpielenRoute
  UeberRoute: typeof UeberRoute
  WarenkorbRoute: typeof WarenkorbRoute
  KategorieSlugRoute: typeof KategorieSlugRoute
  ListingIdRoute: typeof ListingIdRoute
  ShopHandleRoute: typeof ShopHandleRoute
  VerkaufenGuideRoute: typeof VerkaufenGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber': {
      id: '/ueber'
      path: '/ueber'
      fullPath: '/ueber'
      preLoaderRoute: typeof UeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spielen': {
      id: '/spielen'
      path: '/spielen'
      fullPath: '/spielen'
      preLoaderRoute: typeof SpielenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorien': {
      id: '/kategorien'
      path: '/kategorien'
      fullPath: '/kategorien'
      preLoaderRoute: typeof KategorienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hilfe': {
      id: '/hilfe'
      path: '/hilfe'
      fullPath: '/hilfe'
      preLoaderRoute: typeof HilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gebuehren': {
      id: '/gebuehren'
      path: '/gebuehren'
      fullPath: '/gebuehren'
      preLoaderRoute: typeof GebuehrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verkaufen/guide': {
      id: '/verkaufen/guide'
      path: '/verkaufen/guide'
      fullPath: '/verkaufen/guide'
      preLoaderRoute: typeof VerkaufenGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$handle': {
      id: '/shop/$handle'
      path: '/shop/$handle'
      fullPath: '/shop/$handle'
      preLoaderRoute: typeof ShopHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorie/$slug': {
      id: '/kategorie/$slug'
      path: '/kategorie/$slug'
      fullPath: '/kategorie/$slug'
      preLoaderRoute: typeof KategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nachrichten': {
      id: '/_authenticated/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof AuthenticatedNachrichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNachrichtenRoute: typeof AuthenticatedNachrichtenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNachrichtenRoute: AuthenticatedNachrichtenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CookiesRoute: CookiesRoute,
  DatenschutzRoute: DatenschutzRoute,
  GebuehrenRoute: GebuehrenRoute,
  HilfeRoute: HilfeRoute,
  ImpressumRoute: ImpressumRoute,
  KategorienRoute: KategorienRoute,
  KontaktRoute: KontaktRoute,
  RedeemRoute: RedeemRoute,
  SpielenRoute: SpielenRoute,
  UeberRoute: UeberRoute,
  WarenkorbRoute: WarenkorbRoute,
  KategorieSlugRoute: KategorieSlugRoute,
  ListingIdRoute: ListingIdRoute,
  ShopHandleRoute: ShopHandleRoute,
  VerkaufenGuideRoute: VerkaufenGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
